version: '3.8'

services:
  postgres:
    container_name: trace-db
    image: postgres:16.0
    networks:
      - trace-network
    environment:
      POSTGRES_DB: trace-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      PGDATA: /data/trace-db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5440:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
  redis:
    image: redis:7.0.13
    networks:
      - trace-network
    container_name: trace-redis-db
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
volumes:
  postgres-db:
    driver: local
  redis-data:
    driver: local
networks:
  trace-network:
    driver: bridge